#!/bin/bash

if [ "$(docker ps --filter="name=GrandeOmega" -aq)" ]; then
  echo "Removing outdated container from list"
  docker rm GrandeOmega
fi

echo "Building Docker container from ./GrandeOmega..."
docker build -q -t grandeomega .